### PR TITLE
Add global css

### PR DESCRIPTION
**Pull request by lmachens**

### CODE REVIEW

**Comment by manuelsanchez2** [comment]
g2g! you are doing well!

**Comment by slawoe** [comment]
lgtm

**Review by mschmauder-hub — APPROVED** [review]
lgtm

**Review by slawoe — APPROVED** [review]

**Review by JoscaWij — APPROVED** [review]
gj 👏 😉

**Review by manuelsanchez2 — APPROVED** [review]
gj

**Pull request merged**
